### ISSUE TITLE
Plugin doesn't work properly with kotlin multiplatform projects.

### ISSUE THREAD

**Issue by Prototik** [YumiProject/yumi-gradle-licenser#1]
~~Plugin skips source sets defined by kotlin multiplatform plugins as internally it doesn't apply `JavaBasePlugin`, which are expected by licenser plugin [here](https://github.com/YumiProject/yumi-gradle-licenser/blob/95ed9f2602f7491adbcfeddfca4ebd321be4a119/src/main/java/dev/yumi/gradle/licenser/YumiLicenserGradlePlugin.java#L46).~~

~~Actually plugin should expect [`JvmEcosystemPlugin`](https://docs.gradle.org/current/javadoc/org/gradle/api/plugins/JvmEcosystemPlugin.html) to be applied, as SourceSetContainer created by it, not `JavaBasePlugin`~~

NVM, Kotlin multiplatform maintains own collection of SourceSets, so treat this issue as "Please add support for kotlin multiplatform projects" as there is no way as I'm currently see to register own set to be processed by licenser.

**Comment by Prototik** [comment]
As a temporal workaround I use this snippet (in subprojects block, kotlin dsl):
```kotlin
    pluginManager.withPlugin("dev.yumi.gradle.licenser") {
        pluginManager.withPlugin("org.jetbrains.kotlin.multiplatform") {
            val kotlin = extensions.getByName<KotlinMultiplatformExtension>("kotlin")
            val licenser = extensions.getByName<YumiLicenserGradleExtension>("license")

            kotlin.sourceSets.all {
                val fakeSourceSet = objects.newInstance<DefaultSourceSet>(name)
                fakeSourceSet.allSource.source(this.kotlin)
                tasks.register(
                    YumiLicenserGradlePlugin.getTaskName(YumiLicenserGradlePlugin.CHECK_TASK_PREFIX, fakeSourceSet),
                    CheckLicenseTask::class, fakeSourceSet, licenser
                )
                project.tasks.register(
                    YumiLicenserGradlePlugin.getTaskName(YumiLicenserGradlePlugin.APPLY_TASK_PREFIX, fakeSourceSet),
                    ApplyLicenseTask::class, fakeSourceSet, licenser
                )
            }
        }
    }
```

**Comment by LambdAurora** [comment]
I'll try to add this soon, thanks for the report!

**Comment by LambdAurora** [comment]
Okay, this should be supported natively starting from version 1.1.0 of the plugin!

**Comment by Laxystem** [comment]
Doesn't seem to work for me when using JVM + WasmJS. K/M 1.9.22, licenser 1.1.0.

**Comment by LambdAurora** [comment]
> Doesn't seem to work for me when using JVM + WasmJS. K/M 1.9.22, licenser 1.1.0.

Do you have a sample repository I can look into for testing?

**Comment by Laxystem** [comment]
> > Doesn't seem to work for me when using JVM + WasmJS. K/M 1.9.22, licenser 1.1.0.
> 
> Do you have a sample repository I can look into for testing?

Oh yeah, just intended to post it. [Here](https://codeberg.org/Laxystem/Gimli/src/commit/587bb4197c292abb0fdd566f32b9ebfc6c404150) ya go (also mirrored on [GitHub](https://github.com/Laxystem/Gimli/tree/587bb4197c292abb0fdd566f32b9ebfc6c404150)). Note code doesn't compile.

**Comment by LambdAurora** [comment]
I'll look into it after work.

**Comment by LambdAurora** [comment]
I've confirmed that this issue still exists when the Kotlin Multiplatform plugin is applied *after* the licenser plugin.
Shouldn't take me much time to fix, turns out I did an oopsie in the code that tries to find the plugin...

**Comment by LambdAurora** [comment]
Version 1.1.1 of the plugin has been released, now there should be no longer priority issues with the Kotlin multiplatform plugin.
